Fixed broken setup due to trying to read missing file
Recieving the following error when trying to rum setup:

Traceback (most recent call last):
  File "lib/python-crpapi/setup.py", line 5, in <module>
  long_description = open('README.rst').read()
  IOError: [Errno 2] No such file or directory: 'README.rst'

Fixing by removing trying to read the README.rst file.